package pojos;
// Generated 28-Nov-2018 16:52:45 by Hibernate Tools 4.3.1



/**
 * TabelStokBarangToko generated by hbm2java
 */
public class TabelStokBarangToko  implements java.io.Serializable {


     private Integer idbarangToko;
     private int idtoko;
     private String namaBarang;
     private int jumlahBarang;
     private int hargaBarang;

    public TabelStokBarangToko() {
    }

    public TabelStokBarangToko(int idtoko, String namaBarang, int jumlahBarang, int hargaBarang) {
       this.idtoko = idtoko;
       this.namaBarang = namaBarang;
       this.jumlahBarang = jumlahBarang;
       this.hargaBarang = hargaBarang;
    }
   
    public Integer getIdbarangToko() {
        return this.idbarangToko;
    }
    
    public void setIdbarangToko(Integer idbarangToko) {
        this.idbarangToko = idbarangToko;
    }
    public int getIdtoko() {
        return this.idtoko;
    }
    
    public void setIdtoko(int idtoko) {
        this.idtoko = idtoko;
    }
    public String getNamaBarang() {
        return this.namaBarang;
    }
    
    public void setNamaBarang(String namaBarang) {
        this.namaBarang = namaBarang;
    }
    public int getJumlahBarang() {
        return this.jumlahBarang;
    }
    
    public void setJumlahBarang(int jumlahBarang) {
        this.jumlahBarang = jumlahBarang;
    }
    public int getHargaBarang() {
        return this.hargaBarang;
    }
    
    public void setHargaBarang(int hargaBarang) {
        this.hargaBarang = hargaBarang;
    }




}


